name: SecretPassage
version: 1.1
main: me.reop.secretPassage.SecretPassage
author: Jorbin
description: A plugin to create secret passages in Minecraft using Spigot 1.21.
api-version: 1.21
commands:
  secretpassage:
    aliases: [sp, spass]
    description: Main command for the SecretPassage plugin.
    usage: |
      /<command> help
      /<command> create <PassageName>
      /<command> destroy <PassageName>
      /<command> toggle <PassageName>
      /<command> list
      /<command> timer <ticks>
      /<command> access <allow|deny|remove> <Name1> (Name2)
      /<command> message <open|close> (message)
      /<command> info <PassageName>
permissions:
  secretpassage.use:
    description: Allows use of SecretPassage commands.
    default: true
  secretpassage.toggle:
    description: Allows toggling of passages.
    default: op
  secretpassage.create.other:
    description: Allows creating passages for others.
    default: op
  secretpassage.destroy.other:
    description: Allows destroying passages of others.
    default: op
  secretpassage.list.other:
    description: Allows listing passages of others.
    default: op
  secretpassage.reset:
    description: Allows resetting passages.
    default: op
  secretpassage.lockout:
    description: Disallows using the plugin.
    default: false
  secretpassage.antilockout:
    description: Overrides lockout permission.
    default: op
  secretpassage.useCommands:
    description: Allows use of SecretPassage commands.
    default: true